const colors = [
  { name: "Crimson", hex: "#dc143c", base: "Red" },
  { name: "Teal", hex: "#008080", base: "Green" },
  { name: "Olive", hex: "#808000", base: "Green" },
  { name: "Goldenrod", hex: "#daa520", base: "Yellow" },
  { name: "Indigo", hex: "#4b0082", base: "Blue" },
  { name: "Coral", hex: "#ff7f50", base: "Orange" },
  { name: "Turquoise", hex: "#40e0d0", base: "Blue" },
  { name: "Slate Blue", hex: "#6a5acd", base: "Blue" },
  { name: "Salmon", hex: "#fa8072", base: "Pink" },
  { name: "Peru", hex: "#cd853f", base: "Brown" },
  { name: "Tomato", hex: "#ff6347", base: "Red" },
  { name: "Orchid", hex: "#da70d6", base: "Purple" },
  { name: "Deep Pink", hex: "#ff1493", base: "Pink" },
  { name: "Khaki", hex: "#f0e68c", base: "Yellow" },
  { name: "Lavender", hex: "#e6e6fa", base: "Purple" },
  { name: "Plum", hex: "#dda0dd", base: "Purple" },
  { name: "Sea Green", hex: "#2e8b57", base: "Green" },
  { name: "Dodger Blue", hex: "#1e90ff", base: "Blue" },
  { name: "Firebrick", hex: "#b22222", base: "Red" },
  { name: "Steel Blue", hex: "#4682b4", base: "Blue" },
  { name: "Beige", hex: "#f5f5dc", base: "Brown" },
  { name: "Maroon", hex: "#800000", base: "Red" },
  { name: "Navy", hex: "#000080", base: "Blue" },
  { name: "Lime", hex: "#00ff00", base: "Green" },
  { name: "Aqua", hex: "#00ffff", base: "Blue" },
  { name: "Fuchsia", hex: "#ff00ff", base: "Pink" },
  { name: "Purple", hex: "#800080", base: "Purple" },
  { name: "Cyan", hex: "#00ffff", base: "Blue" },
  { name: "Mint Cream", hex: "#f5fffa", base: "Green" },
  { name: "Misty Rose", hex: "#ffe4e1", base: "Pink" },
  { name: "Peach Puff", hex: "#ffdab9", base: "Orange" },
  { name: "Pale Green", hex: "#98fb98", base: "Green" },
  { name: "Pale Violet Red", hex: "#db7093", base: "Pink" },
  { name: "Medium Orchid", hex: "#ba55d3", base: "Purple" },
  { name: "Medium Sea Green", hex: "#3cb371", base: "Green" },
  { name: "Medium Slate Blue", hex: "#7b68ee", base: "Blue" },
  { name: "Medium Spring Green", hex: "#00fa9a", base: "Green" },
  { name: "Medium Turquoise", hex: "#48d1cc", base: "Blue" },
  { name: "Medium Violet Red", hex: "#c71585", base: "Pink" },
  { name: "Midnight Blue", hex: "#191970", base: "Blue" },
  { name: "Moccasin", hex: "#ffe4b5", base: "Yellow" },
  { name: "Navajo White", hex: "#ffdead", base: "Yellow" },
  { name: "Old Lace", hex: "#fdf5e6", base: "Yellow" },
  { name: "Papaya Whip", hex: "#ffefd5", base: "Yellow" },
  { name: "Powder Blue", hex: "#b0e0e6", base: "Blue" },
  { name: "Rosy Brown", hex: "#bc8f8f", base: "Brown" },
  { name: "Saddle Brown", hex: "#8b4513", base: "Brown" },
  { name: "Sandy Brown", hex: "#f4a460", base: "Brown" },
  { name: "Sienna", hex: "#a0522d", base: "Brown" },
  { name: "Sky Blue", hex: "#87ceeb", base: "Blue" },
  { name: "Snow", hex: "#fffafa", base: "White" },
  { name: "Tan", hex: "#d2b48c", base: "Brown" },
  { name: "Thistle", hex: "#d8bfd8", base: "Purple" },
  { name: "Wheat", hex: "#f5deb3", base: "Yellow" },
  { name: "White Smoke", hex: "#f5f5f5", base: "White" },
  { name: "Yellow Green", hex: "#9acd32", base: "Green" },
  { name: "Chocolate", hex: "#d2691e", base: "Brown" },
  { name: "Dark Salmon", hex: "#e9967a", base: "Pink" },
  { name: "Light Coral", hex: "#f08080", base: "Pink" },
  { name: "Dark Red", hex: "#8b0000", base: "Red" },
  { name: "Light Salmon", hex: "#ffa07a", base: "Pink" },
  { name: "Dark Orange", hex: "#ff8c00", base: "Orange" },
  { name: "Light Pink", hex: "#ffb6c1", base: "Pink" },
  { name: "Dark Khaki", hex: "#bdb76b", base: "Yellow" },
  { name: "Light Yellow", hex: "#ffffe0", base: "Yellow" },
  { name: "Dark Goldenrod", hex: "#b8860b", base: "Yellow" },
  { name: "Light Goldenrod Yellow", hex: "#fafad2", base: "Yellow" },
  { name: "Dark Olive Green", hex: "#556b2f", base: "Green" },
  { name: "Light Green", hex: "#90ee90", base: "Green" },
  { name: "Dark Sea Green", hex: "#8fbc8f", base: "Green" },
  { name: "Light Sea Green", hex: "#20b2aa", base: "Green" },
  { name: "Dark Slate Gray", hex: "#2f4f4f", base: "Gray" },
  { name: "Light Slate Gray", hex: "#778899", base: "Gray" },
  { name: "Dark Turquoise", hex: "#00ced1", base: "Blue" },
  { name: "Light Cyan", hex: "#e0ffff", base: "Blue" },
  { name: "Dark Violet", hex: "#9400d3", base: "Purple" },
  { name: "Light Steel Blue", hex: "#b0c4de", base: "Blue" },
  { name: "Dark Orchid", hex: "#9932cc", base: "Purple" },
  { name: "Light Blue", hex: "#add8e6", base: "Blue" },
  { name: "Dark Magenta", hex: "#8b008b", base: "Purple" },
  { name: "Light Sky Blue", hex: "#87cefa", base: "Blue" },
  { name: "Dark Cyan", hex: "#008b8b", base: "Blue" },
  { name: "Light Coral", hex: "#f08080", base: "Pink" },
  { name: "Dark Blue", hex: "#00008b", base: "Blue" },
  { name: "Light Salmon", hex: "#ffa07a", base: "Pink" },
  { name: "Dark Red", hex: "#8b0000", base: "Red" },
  { name: "Light Pink", hex: "#ffb6c1", base: "Pink" },
  { name: "Dark Khaki", hex: "#bdb76b", base: "Yellow" },
  { name: "Light Yellow", hex: "#ffffe0", base: "Yellow" },
  { name: "Dark Goldenrod", hex: "#b8860b", base: "Yellow" },
  { name: "Light Goldenrod Yellow", hex: "#fafad2", base: "Yellow" },
  { name: "Dark Olive Green", hex: "#556b2f", base: "Green" },
  { name: "Light Green", hex: "#90ee90", base: "Green" },
  { name: "Dark Sea Green", hex: "#8fbc8f", base: "Green" },
  { name: "Light Sea Green", hex: "#20b2aa", base: "Green" },
  { name: "Dark Slate Gray", hex: "#2f4f4f", base: "Gray" },
  { name: "Light Slate Gray", hex: "#778899", base: "Gray" },
  { name: "Dark Turquoise", hex: "#00ced1", base: "Blue" },
  { name: "Light Cyan", hex: "#e0ffff", base: "Blue" },
  { name: "Dark Violet", hex: "#9400d3", base: "Purple" },
  { name: "Light Steel Blue", hex: "#b0c4de", base: "Blue" },
  { name: "Dark Orchid", hex: "#9932cc", base: "Purple" },
  { name: "Light Blue", hex: "#add8e6", base: "Blue" },
  { name: "Dark Magenta", hex: "#8b008b", base: "Purple" },
  { name: "Light Sky Blue", hex: "#87cefa", base: "Blue" },
  { name: "Dark Cyan", hex: "#008b8b", base: "Blue" },
  { name: "Light Coral", hex: "#f08080", base: "Pink" },
  { name: "Dark Blue", hex: "#00008b", base: "Blue" }
];
document.addEventListener("DOMContentLoaded", () => {
  const colorContainer = document.getElementById("colorContainer");

  colors.forEach(color => {
    const colorStrip = document.createElement("div");
    colorStrip.className = "color-strip";
    colorStrip.style.background = color.hex;
    colorStrip.textContent = `${color.name} (${color.hex})`;
    colorContainer.appendChild(colorStrip);
  });
});
